{% set version = "0.2.1" %}

package:
  name: agate-remote
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/agate-remote/agate-remote-{{ version }}.tar.gz
  sha256: 746c7da09744696a56a95bb1d1d7c8c9d8cb3bd40d6c40cede371e0e749442fb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - agate >=1.5.0
    - requests >=2.9.1

test:
  imports:
    - agateremote

about:
  home: http://agate-remote.readthedocs.org/
  license: MIT
  license_file: COPYING
  license_family: MIT
  # license_file: COPYING - No MANIFEST.in - see https://github.com/wireservice/agate-remote/pull/13
  summary: agate-remote adds read support for remote files to agate.
  doc_url: http://agate-remote.readthedocs.org/
  dev_url: https://github.com/wireservice/agate-remote

extra:
  recipe-maintainers:
    - pmlandwehr
