{% set version = "0.2.0" %}

package:
  name: agate-remote
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/agate-remote/agate-remote-{{ version }}.tar.gz
  sha256: 06a3ce50634ed3e2893139469dddc470ade65f448cd65e2c9eca65a8d36109a2

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - agate >=1.5.0
    - requests >=2.9.1

test:
  imports:
    - agateremote

about:
  home: http://agate-remote.readthedocs.org/
  license: MIT
  license_family: MIT
  # license_file: COPYING - No MANIFEST.in - see https://github.com/wireservice/agate-remote/pull/13
  summary: 'agate-remote adds read support for remote files to agate.'
  doc_url: http://agate-remote.readthedocs.org/
  dev_url: https://github.com/wireservice/agate-remote

extra:
  recipe-maintainers:
    - pmlandwehr
