travis:
  secure:
    BINSTAR_TOKEN: dAD0zOSRCAGV3O0C7i7FKYa8TYNdZvKXxnS8HPdJ2bdMVcujIVN//TrWs6i8PkxEPkO5VhpIui5X5vYqhgrUbYJTc+HRriyCjJsrsacol+5cba90/Rpo/3FbU1dlBWyjaDRjskIRV+nyhosAOTCC3uj1ms6a6elGvMlwEWqM5dN5+wA/6VVCi0IOZvAqlqhjoT6P6T4f3oIEMBpdCpbdae1HBx4+EHrGgyME4iH9ZxWdNzqi+9/ZBPLMS2n5vMkfsVPD18avg4CO1sTl8OsDTPjTkoblWAIRKEgcWlM8Fh+WddeOp9xgL89seSQ9iRRKbNOr/QTm9wUn17b3Yv5PKLU9/ibKlnrDepf2TeneKemF0ooJbecyk8/uYKQ7piUCZNLWf/WGcRsN2qz2XcOj7la2U+pF7NtavR51vwKzUFP1Q9QZw5MCyCahBAzBXOCCWf3BDkGceRpor2jlwIA1yH/WJnvsh0M7JULWrO9brXrZtPTwQLH4xizyOd98yXONOsVoQLIY6jfji1g59v+a/vS8Q20VHjr8qg617bXQHA17vT6xlcZE7EOKxqHBq61nyDkqNbosS9Vfqtbnm4IDZk1IaRk6SuL6/LDfZpzGCkBahVMJ9TKKTzGxTFn4AKS5zendecs2Zz0ZtS1ITXDb4NWtQdn24618lazd2oRFYZQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
