travis:
  secure:
    BINSTAR_TOKEN: eVndTrGaGr+w334UYtMmb9PXGHVchsBW6sWSRhhP6Tt+lAYE7B/G39IaxmzILVTTq7UwDHsENedAnzhZqMVnkJRM6scYH1CcESOOZJfD51TBDwJKwe9fHRx/UdNj7GxQxuT3+B8uAPLHuApYT0jSG5iFUH4HRYPBSnTA8+O+aisHwRQINOuCllKiQsau30NZoxKfRmUnq8gwioITtSrNmMz0D3LzK+BidYmydvcfpq3Dd8eiWao1K5hK+ol0Hx0+1fvU1GDdWS21vXshd3PvXi2f0zWnhS59ke6UrPvRkIc65jMfqAwZPmKn54bVZdwbBVSEdywjQpRB5yeqxpUyZ7P/QiavLcW2ZItVACLd75nLzcej5grmp3DlU3jwK34Tb4vhNk3NknPGZg3OjOdp+bw7o8WBjHaAJ9KeVymvp+z6xHrlrvOxyHde1eU0ayOJXjY498LhZN5soJikM1yGppNatE5DQuOSWeexVIYhu2STl+6gfQAj7UQ8DM6k4vn2JAJZndxHnwQVhlCC847sB47ckhYMuVgRP4A0fbSHB2RFPddvlkf84c9uvmPGKxW4vyCSOeyx+3RFoQFju9ViiB114mHpPOPYDFGO9jpwz57RSVXvbEbztbtjMvSmQc/t3aTyB1txVqLOdBkuu5ypabdos1VGyVeifkD2aaAg4FM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
